"""add tenant support

Revision ID: dc7a488dc538
Revises: 9f72b1fd8552
Create Date: 2026-03-31 16:55:21.431391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7a488dc538'
down_revision: Union[str, Sequence[str], None] = '9f72b1fd8552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.execute("UPDATE restaurants SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.alter_column('restaurants', 'tenant_id', nullable=False)
    op.add_column('restaurants', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('restaurants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('restaurants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_tenant_id'), 'restaurants', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('restaurants_user_id_fkey'), 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('restaurants', 'user_id')
    # Add tenant_id as nullable first
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # Insert default tenant if not exists
    op.execute("INSERT INTO tenants (id, name, slug, is_active, created_at) VALUES (1, 'Default Tenant', 'default', 1, NOW()) ON CONFLICT (id) DO NOTHING")
    # Update existing users to have tenant_id=1
    op.execute("UPDATE users SET tenant_id = 1 WHERE tenant_id IS NULL")
    # Then make it not null
    op.alter_column('users', 'tenant_id', nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'tenant_id')
    op.add_column('restaurants', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key(op.f('restaurants_user_id_fkey'), 'restaurants', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_restaurants_tenant_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'is_active')
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'email')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'address')
    op.drop_column('restaurants', 'description')
    op.drop_column('restaurants', 'tenant_id')
    # ### end Alembic commands ###
