"""add_user_invitations_table

Revision ID: b790dd0fbced
Revises: 26961e75e149
Create Date: 2026-04-04 18:07:33.477303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b790dd0fbced'
down_revision: Union[str, Sequence[str], None] = '26961e75e149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('restaurant_tenant_id', sa.UUID(), nullable=True))
    op.add_column('agreements', sa.Column('company_tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agreements', 'tenants', ['company_tenant_id'], ['id'])
    op.create_foreign_key(None, 'agreements', 'tenants', ['restaurant_tenant_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'tenants', ['tenant_id'], ['id'])
    op.add_column('employees', sa.Column('company_tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'tenants', ['company_tenant_id'], ['id'])
    op.add_column('meal_logs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'meal_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('restaurants', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'restaurants', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'tenant_id')
    op.drop_constraint(None, 'meal_logs', type_='foreignkey')
    op.drop_column('meal_logs', 'tenant_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_tenant_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.drop_column('agreements', 'company_tenant_id')
    op.drop_column('agreements', 'restaurant_tenant_id')
    # ### end Alembic commands ###
